# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dp_normal_mix <- function(x, N, alpha, lambda, kappa, nu, Omega) {
    .Call('_plmix_dp_normal_mix', PACKAGE = 'plmix', x, N, alpha, lambda, kappa, nu, Omega)
}

